# Generated by Django 5.0.2 on 2024-10-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_receipe_receipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_image',
        ),
    ]
